project_name: openweather-influxdb-writer
before:
  hooks:
    - go mod download
builds:
  - binary: openweather-influxdb-writer
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - 386
      - amd64
      - arm
      - arm64
    goarm:
      - 5
      - 6
    ignore:
      - goos: windows
        goarch: arm64
      - goos: windows
        goarm: 5
archives:
  - format_overrides:
      - goos: windows
        format: zip